; PlatformIO Project Configuration File
;
; BatteryCharger unit test (manual hardware test)

[platformio]
default_envs = adafruit_feather_esp32_v2
src_dir = BatteryChargerSimpleTest

[env]
; Use the latest stable Arduino-ESP32 platform, which includes support for the ESP32-C6 variants
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.34
; if you want to use the default platformio platform, uncomment the line below 
; and comment out the line above, but make sure to select a recent version of 
; the platform that includes ESP32-C6 support (e.g. 3.2.0 or later)
; platform = espressif32@3.2.0
framework = arduino
monitor_speed = 115200

lib_extra_dirs = ../../..
lib_deps =
    BatteryCharger

[env:adafruit_feather_esp32_v2]
board = adafruit_feather_esp32_v2

[env:waveshare_esp32_s3_zero]
board = waveshare_esp32_s3_zero

[env:makergo_c6_supermini]
board = makergo_c6_supermini


